# -*- coding: utf-8 -*-
"""machinelearning03

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LMaPXwrYZEcD8j2pRWAHqt-GzRi4esfI
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
df = pd.read_csv("/content/kc_house_data.csv")
X = df["sqft_living"].values
y = df["price"].values
# Start values
w = 0
b = 0
learning_rate = 0.00000001
losses = []
# Gradient Descent
for i in range(1000):

    prediction = w * X + b
    error = prediction - y
    # Gradient
    dw = (2 / len(y)) * np.sum(X * error)
    db = (2 / len(y)) * np.sum(error)
    # Update
    w = w - learning_rate * dw
    b = b - learning_rate * db
    # Calculate loss
    loss = np.mean(error ** 2)
    losses.append(loss)

print(f"Optimal Weight (slope): {w:.4f}")
print(f"Optimal Bias (intercept): {b:.4f}")

# Plot gradient descent
plt.plot(losses)
plt.xlabel("Iterations")
plt.ylabel("Loss")
plt.title("Gradient Descent Graph")
plt.show()